### ISSUE TITLE
NoSuchMethodError with older version of magnolia

### ISSUE THREAD

**Issue by ghostdogpr** [softwaremill/tapir#177]
I started to get runtime errors after adding tapir to my project. It turned out that I was using Magnolia 0.10.0 in my project and Tapir brings Magnolia 0.11.0. There must be some incompatibility between the two resulting in these runtime errors.

```
java.lang.NoSuchMethodError: magnolia.TypeName.<init>(Ljava/lang/String;Ljava/lang/String;)V
```

The problem was solved after upgrading to 0.11.0 but leaving this here in case someone has the same issue. Maybe the doc should explicitly mention the specific version of Magnolia required.

**Comment by adamw** [comment]
hm ... that's a bit weird, shouldn't the transitive dependency of tapir (the only one, and still there are problems ... ;) ) update the version of magnolia in your project as well?

**Comment by ghostdogpr** [comment]
I had the older version explicitly declared. Anyway I created this just in case someone has the same problem and searches for this error, I’ll close it.

**Comment by guizmaii** [comment]
Thanks @ghostdogpr! I had this error in my project without even using Tapir and your issue here helped me to solve the error. 🙂
