### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dharm82465** [softwaremill/tapir#1576]
Tapir version: 0.19.0-M13

Scala version: 2.12.11

**Describe the bug**

After migrating from Tapir 0.16.16 to 0.19.0-M13, the application fails to start and throw the following exception:

```
[error] Exception in thread "main" java.lang.NoSuchMethodError: cats.kernel.CommutativeSemigroup.$init$(Lcats/kernel/CommutativeSemigroup;)V
[error] 	at cats.UnorderedFoldable$$anon$1.<init>(UnorderedFoldable.scala:81)
[error] 	at cats.UnorderedFoldable$.<init>(UnorderedFoldable.scala:81)
[error] 	at cats.UnorderedFoldable$.<clinit>(UnorderedFoldable.scala)
[error] 	at cats.data.NonEmptyListInstances$$anon$2.<init>(NonEmptyList.scala:723)
[error] 	at cats.data.NonEmptyListInstances.<init>(NonEmptyList.scala:723)
[error] 	at cats.data.NonEmptyList$.<init>(NonEmptyList.scala:642)
[error] 	at cats.data.NonEmptyList$.<clinit>(NonEmptyList.scala)
[error] 	at io.circe.Decoder$.<init>(Decoder.scala:460)
[error] 	at io.circe.Decoder$.<clinit>(Decoder.scala)
```

What is the problem?

The app currently depends on cats 2.1.1, I wonder if this is due to version conflicts and is there a way to fix this error

**How to reproduce?**

Maybe you can provide code to reproduce the problem?

**Additional information**

**Comment by adamw** [comment]
Latest tapir depends on:

```
"org.typelevel" %%% "cats-core" % "2.6.1",
"org.typelevel" %%% "cats-effect" % "3.2.9",
```

so please try with these versions

**Comment by dharm82465** [comment]
Thank you @adamw you suggestion works for me
