### PR TITLE
Add codecs for vectors and sets

### PR DESCRIPTION
**Pull request by matwojcik**
After migration to 0.13 there were compilation errors due to lack of `Codec[List[T], Set[U], CF]`, which were present for `CodecForMany` in 0.12. This MR should resolve this.

### CODE REVIEW

**Comment by matwojcik** [comment]
@adamw pls take a look ;)

**Comment by adamw** [comment]
Thanks! Released in 0.14.0.
